# Generated by Django 4.1.7 on 2023-04-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.DateField()),
            ],
            options={
                'verbose_name': 'Project_details',
                'verbose_name_plural': 'Project_detailss',
                'db_table': 'Project_details_table',
                'managed': True,
            },
        ),
    ]
